### ISSUE TITLE
Unicode version 12.1

### ISSUE THREAD

**Issue by data-man** [BurntSushi/ucd-generate#10]
Please update.

**Comment by BurntSushi** [comment]
Could you please say more? Part of the input to `ucd-generate` is the Unicode data files themselves. `ucd-generate` doesn't bundle them.

**Comment by data-man** [comment]
ucd-util

**Comment by BurntSushi** [comment]
Fixed in https://github.com/BurntSushi/ucd-generate/commit/f5c409990efd0b02beaae6b3e5930bcfa3a61020, which is in `ucd-util 0.1.4` on crates.io.
