### ISSUE TITLE
`codepoint_to_codepoints` tables are needlessly wasteful

### ISSUE THREAD

**Issue by thomcc** [BurntSushi/ucd-generate#33]
This output is used by the non-`--simple` case mapping tables, and the `--all-pairs` case folding table. 

I ended up going on a bit of a journey while looking into this one, mostly trying to figure out why it helped more than I had expected. The TLDR is that going from &[(char, &[char])] to &[(char, [char;3])] saves a lot of space -- more than you'd naively expect, and probably reduces startup time as well (on some platforms, given some set of compiler flags, etc).

Note: All sizes are given for 64 bit, but the overhead is still present on 32 bit, just slightly smaller. Additionally, do a mental `s/char/u32/` where necessary if you're not outputting tables with char literals directly (e.g. `--chars`) -- it makes no difference.

### I need to be convinced that it's bad.

The most obvious way this is bad is that these tables are output a slice of `(char, &[char])`. This occupies 24 bytes per entry (4 + 8 + 8 aligned up to 8), which is quite bad, but not even the whole story -- each entry also points to an out-of-line array, which occupies between 4 and 12 bytes. Being generous and rounding down to 4 (as most are 4 for most uses), this is still substantial, and means we have 28 bytes of table data per entry.

However, there's a more subtle way it's bad. When you store static arrays containing lot of pointers in this manner, and compile as a shared library, it can cause all the pointers to have to be relocated when the library is loaded. This be slow and contribute to further binary bloat (especially huge tables like these), and it can prevent the table from being placed in read-only memory (not that important probably, but cases like `regex-capi` might care).

For more on this, see https://akkadia.org/drepper/dsohowto.pdf but note that it's old, that many of its suggestions are either irrelevant or impossible for Rust, and that some of the things that he says don't cause issues in C, seem to still cause them for rust. `readelf` is the only real source of truth here (... well, for me it's been anyway).

### Yes, yes, okay, what's your plan.

Instead of `(char, &[char])`, we should store entries as `(char, [char; 3])`. This would give us 16 bytes per entry, with no data stored out-of-line. We can append trailing NULs to unused portions of the `[char; 3]`, which simultaneously solves the issues of "how do we recover `entry.1.len()`" and "what do we put in unused portions of entry.1".

This means you need slightly more complex logic to get the `&[char]` back, but in exchange you get reduced binary size and better cache locality (both because more entries fit into a single cache line, and because you no longer have to chase a pointer to get the data for a given entry).

There are other options slight variations here, but last night before I called it quits on writing this, I decided for some reason that this was where I should start deleting... Essentially: NUL is a little dodgy, Option<char> would work but forces a perf hit without unsafe (example: `entry.1[0]` should not need a check), and `0!` or `0x110000` would work for u32 output. That said, it seems very very unlikely that using NUL like this is a problem.

### Explain how good of an idea it is, using numbers.

Doing this would reduce the various tables to about 56% of their former size. In theory it's between 57% and 44% depending on how many tables use longer &[char] slices, but in practice the non-singleton entries are very rare for all tables. Concretely, the case-folding-simple --all-chars table goes from 78,728 bytes to 44,768 bytes -- a reduction to 56.8% of the former size.

However, this is ignoring any size gained by removing overhead caused by the binary format and relocation information!

In practice, I've verified that at least on x86_64 linux when a library exposing a single function boiling down to `CASE_FOLDING_TABLE.get(usize)`, 102,472 bytes are saved by the change in representation -- and the shared library file goes from 154,600 bytes to 52,128 (which is essentially optimal without material changes to the algorithm). It's hard to be certain, but that's somewhere around a reduction to 33% of the old size.

Note that the verification I did was based on making this change via regex-replace `&[x]` => `[x, 0, 0]` (and so on for 2 and 3) on the existing table table data, so it's not like I'm sitting on a patch for this.

### Please, ramble for two more paragraphs, but say very little

... Honestly, 44k for this data still feels pretty terrible to me, but this seems the easiest possible change without coming up with a new algorithm for it. I would be interested in options for encoding this data with lower overhead still though.

More broadly, there are also other changes that could be made to reduce relocation overhead for some tables, but this is probably the biggest (maybe some property value things?). That said, it's probably worth considering for some of the ones used by regex-syntax...

**Comment by BurntSushi** [comment]
Wow, great analysis! Your suggestion of `[char; 3]` sounds great to me, with some concerns/ideas:

* We should leave the existing modes in tact and add `[char; 3]` as a new output mode to avoid breaking changes.
* It definitely seems worthwhile to migrate regex-syntax to this new representation.
* I'm mildly worried about using NUL as a sentinel since it is also a valid codepoint. But it's pretty rare for NUL to be in a Unicode property. (I know it's in some properties, e.g., like `\p{any}` or `\p{ascii}`.) But I think that's easy to solve by just having `ucd-generate` report an error if the codepoint table contains NUL.
* For `u32`, using `!0` as a sentinel sounds good, and serves as a nice work-around for the odd case where NUL is a valid value.
