### ISSUE TITLE
Hyphens next to underscores are considered medial in character names

### ISSUE THREAD

**Issue by dscorbett** [BurntSushi/ucd-generate#6]
`character_name_normalize` only treats a hyphen as medial if it is not next to a space, but UAX44-LM2 defines medial as “immediately between two letters”. That means that, for example, `"tibetan_letter_-a"` should match `"TIBETAN LETTER -A"`, not `"TIBETAN LETTER A"`.

http://play.rust-lang.org/?gist=b509b7c2ea044330a0062afd20e72a15&version=stable&mode=debug&edition=2015

**Comment by BurntSushi** [comment]
Thanks for the bug report! Fixed in https://github.com/BurntSushi/ucd-generate/commit/aedf699c08716f410198bd815457dc53c2b1e5f4
